### PR TITLE
Failing test to demonstrates values with newlines throw exceptions

### PR DESCRIPTION
**Pull request by AndrewIngram**

### CODE REVIEW

**Comment by victorquinn** [comment]
Oof that's not good! Thanks for the test, we'll have to figure out a solution here!

My gut says to just safely escape the newlines the unescape as we pull the document out of Memcache, but this could potentially break compatibility with other Memcache libraries. We want to make sure we're putting data in and pulling data out the same as all the other libraries so folks can switch or write from one platform and read from another.

This is a long-winded way of saying this 100% needs to be fixed, and fast, but the right answer is not glaringly obvious and simple.

**Comment by victorquinn** [comment]
Although actually, that test passed in CI which is peculiar.

What platform were you running your test on to have it fail?

**Comment by AndrewIngram** [comment]
I was running it on OSX Yosemite and Sierra (work and home computers) with Node 6.9.3

I tried stealing the escape/unescape code from the other node memcached library, but dropping it in wasn't as trivial as I hoped.

**Comment by victorquinn** [comment]
Cool, able to reproduce locally, looks like Travis wasn't appropriately running the tests which is why it passed. I'll fix that too!

**Pull request merged**
