### PR TITLE
Implement cachedump(), fix items()

### PR DESCRIPTION
**Pull request by theogravity**
https://github.com/victorquinn/memcache-plus/issues/27

### CODE REVIEW

**Comment by theogravity** [comment]
Is Travis CI actually running the unit tests, or is it just building the docs? 

Kind of concerned that the tests in general (outside of my changes), fail.

**Comment by theogravity** [comment]
These are the errors I'm seeing in the tests (I increased to 5s timeouts on my end to make sure its not an execution time issue)

```
  1) Client decr should throw an error if called with a key that is too long:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:785:90)
  

  2) Client decr should work without a decrement value:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  3) Client decr should work with a decrement value:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  4) Client append should throw an error if called with a key that is too long:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:1005:92)
  

  5) Client append should work as normal:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  6) Client append should work should behave properly when append over non-existent key:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  7) Client prepend should throw an error if called with a key that is too long:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:1058:93)
  

  8) Client prepend should work as normal:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  9) Client prepend should work should behave properly when prepend over non-existent key:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
 ```

**Comment by theogravity** [comment]
One recommendation is to make sure `done` is being used at the end of the promise chain in the tests, eg

```
it('...', function(done) {
   somePromise().then(function(data) {
     expect(data).to.be.defined;
     done();
   });
})
```

**Comment by victorquinn** [comment]
Hmm, that seems troubling. 

FYI you don't need to call `done()` at the end of a Promise chain, you can also just return a Promise and Mocha understands that and waits for the Promise to finish. If it's not, it is likely indicating an actual bug has been introduced..

**Comment by victorquinn** [comment]
Although, to answer your other question, yes Travis does run the tests and they appear to pass there so things are likely alright. I'll merge and then run them locally and see if there are issues and fix if there are.

**Comment by theogravity** [comment]
Thanks. What version of node are you running? I have a feeling the memcache ver is not so much an issue

**Comment by victorquinn** [comment]
Hmm, I'm running node 6.9.1 on my local machine and Travis is testing against 6.9.1,  5.12.0, and 4.6.1 with no errors.

For memcached, Travis seems to have 1.4.13 and I'm running 1.4.31-1 locally.

Very peculiar...

**Comment by theogravity** [comment]
Hrm, tried with 6.9.1, same issue. It seems majority of the failures are on the newer functions (incr/decr/add/append/prepend)

```

  1) Client incr should throw an error if called with a key that is too long:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:729:90)
  

  2) Client incr should work without an increment value:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  3) Client incr should work with an increment value:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  4) Client decr should throw an error if called with a key that is too long:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:785:90)
  

  5) Client decr should work without a decrement value:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  6) Client decr should work with a decrement value:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  7) Client add should throw an error if called with a key that is too long:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:899:89)
  

  8) Client add should work with a brand new key:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  9) Client add should work should behave properly when add over existing key:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  10) Client append should throw an error if called with a key that is too long:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:1005:92)
  

  11) Client append should work as normal:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  12) Client append should work should behave properly when append over non-existent key:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  13) Client prepend should throw an error if called with a key that is too long:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:1058:93)
  

  14) Client prepend should throw an error if called with a non-string key:
     AssertionError: expected [Function] to throw an error
    at Context.<anonymous> (test/client.js:1062:79)
  

  15) Client prepend should work as normal:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  16) Client prepend should work should behave properly when prepend over non-existent key:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
 
```

**Comment by theogravity** [comment]
I'll check with a co-worker tomorrow if they can try running the tests to see if they get the same result or not. It's very possible my machine just needs a pure OS reset due to all the mods I've done to it.

**Pull request merged**
